name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install webpack-cli
      run: npm install -D webpack-cli
      
    - name: Install babel-loader
      run: npm install --save-dev babel-loader @babel/core @babel/preset-env

    - name: Build
      run: |
        npm install
        npx webpack
